//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public int Resource_ID { get; set; }
        public string Resource_Name { get; set; }
        public string Billing_Type { get; set; }
        public string City { get; set; }
        public string Shore { get; set; }
    }
}
